spring:
  application:
    name: microservice-file-upload
  servlet:
    multipart:
      max-file-size: 2000MB  #默认1M
      max-request-size: 2500MB #默认10M
server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #defaultZone设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。多个地址间可用,分隔。
  instance:
    prefer-ip-address: true

#上传大文件时，要将超时时间设置长一些，否则会报超时异常
#通过zuul上传大文件时，添加/zuul前缀
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
