server:
  port: 8000
spring:
  application:
    name: microservice-provider-user-my-metadata #全部小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema:
    - classpath:schema.sql
    data:
    - classpath:data.sql
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.study: debug

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      #自定义的元数据，key/value都可以随便写
      mydata: 123
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka