spring:
  application:
    name: microservice-hystrix-turbine
server:
  port: 8031

eureka:
  client:
    register-with-eureka: false  #表示是否将自己注册到Eureka Server上，默认为true。由于当前应用就是Eureka Server，故而设置为false
    fetch-registry: false  #表示是否从Eureka Sever获取注册信息，默认为true。因为这是一个单点的Eureka Server,不需要同步其他的Eureka Server节点的数据，故而设置为false
    service-url:
      defaultZone: http://localhost:8761/eureka  #defaultZone设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。多个地址间可用,分隔。
  instance:
    prefer-ip-address: true
turbine:
  appConfig: microservice-consumer-movie,microservice-consumer-movie-feign-hystrix-fallback-stream
  clusterNameExpression: "'default'"
##使用以上配置，Turbine会在Eureka Server中找到  microservice-consumer-movie,microservice-consumer-movie-feign-hystrix-fallback-stream
##这两个微服务，并聚合两个微服务的监控数据
