spring:
  application:
    name: microservice-gateway-zuul
server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh
zuul:
  ribbon-isolation-strategy: thread