spring:
  application:
    name: microservice-consumer-movie
server:
  port: 8010

  
eureka:
  instance:
    ##instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

