spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback-stream
server:
  port: 8020
##开启feign的hystrix支持
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    ##instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

